# Generated by Django 5.0.1 on 2026-02-05 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Student ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering')], max_length=2, verbose_name='Department')),
                ('course', models.CharField(choices=[('CS_GENERAL', 'Computer Science'), ('CS_AI_ML', 'CSE - AI/ML'), ('CS_IOT', 'CSE - IOT'), ('CS_AIDS', 'CSE - AIDS'), ('CS_DS', 'CSE - DS'), ('CE_CONSTRUCTION', 'Construction Engineering'), ('CE_STRUCTURAL', 'Structural Engineering'), ('CE_GEOTECHNICAL', 'Geotechnical Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering')], max_length=20, verbose_name='Course')),
                ('year', models.CharField(choices=[('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=10, verbose_name='Year')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=1, verbose_name='Semester')),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Division')),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Roll Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('teacher', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('photo_samples_taken', models.BooleanField(default=False, verbose_name='Photo Sample Taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
    ]
