# Generated by Django 5.0.1 on 2026-02-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(auto_now_add=True, verbose_name='Training Date')),
                ('model_file', models.CharField(max_length=255, verbose_name='Model File Path')),
                ('num_students', models.IntegerField(verbose_name='Number of Students')),
                ('num_images', models.IntegerField(verbose_name='Number of Images')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Model Accuracy')),
                ('notes', models.TextField(blank=True, verbose_name='Training Notes')),
            ],
            options={
                'verbose_name': 'Training Model',
                'verbose_name_plural': 'Training Models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Time')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], default='P', max_length=1, verbose_name='Status')),
                ('confidence', models.FloatField(help_text='Face recognition confidence percentage', verbose_name='Recognition Confidence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-time'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
